version: '3'
services:
  app:
    image: mihirinventam/github-workflow:latest
    container_name: github-workflow
    environment:
      NODE_ENV: development
      DB_HOST: mysqldb  # This should match the database container name
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: yourpassword
      DB_NAME: yourdbname
    depends_on:
      - mysqldb
    ports:
      - "9999:9999"  # Exposing app port
    restart: always

  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: yourdbname
    ports:
      - "3306:3306"  # Exposing MySQL port
    restart: always
