name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Change this if your default branch is different.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_IMAGE_TEMP }} .
          docker push ${{ secrets.DOCKER_IMAGE_TEMP }}
          
      - name: SSH connection with AWS EC2 instance
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_SECRET_KEY }}  # Make sure this contains the private key, not the AWS secret key
          REMOTE_HOST: ${{ secrets.AWS_HOST_TEMP }}
          REMOTE_USER: ${{ secrets.AWS_USER_TEMP }}
          DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}

      - name: Deployment 
        run: |
          echo "Deploying to EC2 instance..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_USER_TEMP }}@${{ secrets.AWS_HOST_TEMP }} << 'EOF'
          # Pull the latest image
          docker pull $DOCKER_IMAGE

          # Stop and remove the existing container if it exists
          docker-compose down

          # Start the new container
          docker-compose up -d
          EOF
