name: temp ssh with server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH connection with Azure VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          SOURCE: './'
          TARGET: /home/mihir31/temp-dir/
          script: |
            cd /home/mihir31/temp-dir/
            echo "Hello this is Mihir & this is test file" >> test.txt
