name: temp ssh with server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH connection with hostinger VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          SOURCE: './'
          TARGET: /root/
          script: |
            cd /root/
            echo "Hello this is Mihir & this is test file" >> test.txt
