name: temp ssh with server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH connection with Azure VM
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.AZURE_VM_PASSWORD }}
          REMOTE_HOST: ${{ secrets.AZURE_HOST }}
          REMOTE_USER: ${{ secrets.AZURE_USER }}
